nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.0.cjs

packageExtensions:
  "@codechecks/client@0.1.12":
    peerDependencies:
      typescript: ">=2.7"
  "@endemolshinegroup/cosmiconfig-typescript-loader@3.0.2":
    peerDependencies:
      typescript: ">=2.7"
  "typechain@3.0.0":
    peerDependencies:
      typescript: ">=3.7.0"
  "@ethereum-waffle/compiler@3.4.0":
    peerDependencies:
      typescript: ">=3.7.0"
  "ethereum-waffle@3.4.0":
    peerDependencies:
      typescript: ">=3.7.0"
  "hardhat-gas-reporter@1.0.4":
    peerDependencies:
      "@codechecks/client": "^0.1.0"
  "@openzeppelin/test-helpers@0.5.15":
    peerDependencies:
      "bn.js": "^4.11.0"
