
# Set the directory to upload to the droplet .
# Release Echidna Link: # https://github.com/crytic/echidna/actions/runs/7571678101/artifacts/1178391144
[input]
directory = "."
timeout = "96h"
jobName = "echidna"

[commands]
setup = '''
if ! command -v slither >/dev/null 2>&1; then
  echo "Installing solc and slither..."
  python3 -m venv ~/venv
  source ~/venv/bin/activate
  pip3 install solc-select slither-analyzer crytic-compile
  solc-select install 0.8.17
  solc-select use 0.8.17
fi

echo "Downloading echidna..."
curl -fsSL -o /tmp/echidna.zip https://github.com/crytic/echidna/actions/runs/7792078773/artifacts/1221990297
echo "Extracting echidna..."
unzip /tmp/echidna.zip -d /tmp
tar -xzf /tmp/echidna.tar.gz -C /tmp
echo "Installing echidna..."
mv -f /tmp/echidna /usr/local/bin
rm /tmp/echidna.tar.gz

echo "Downloading medusa..."
sudo apt-get update; sudo apt-get install -y golang-go
git clone git@github.com:crytic/medusa.git
go build
chmod +x medusa
sudo mv -f medusa /usr/local/bin

if ! command -v forge >/dev/null 2>&1; then
  echo "Installing foundry..." 
  curl -L https://foundry.paradigm.xyz | bash
  source /.bashrc
  foundryup
fi

echo "Prerequisites installed successfully!"
echo "Forge version:"
forge --version
'''

# This command is run from the input directory
# after the setup script completes.
run = "source /.bashrc && forge --version && make ec"
