[profile.default]

# The source directory
src = 'contracts'

# The test directory
test = 'tests'

# The artifact directory
out = 'artifacts'

# The fs permission
fs_permissions = [
  { access = "read-write", path = "./" },
]

# Sets the concrete solc version to use
# This overrides the `auto_detect_solc` value
solc_version = '0.8.17'
evm_version = 'london'
auto_detect_solc = false
evm_version = 'london'
