name: "Assign Reviewers"
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: "Assign Team"
        uses: rowi1de/auto-assign-review-teams@v1.0.1
        with:
          repo-token: ${{ secrets.AUSTIN_PERSONAL_API_KEY }}
          teams: "smart-contract-cr" # only works for GitHub Organisation/Teams
          include-draft: false # Draft PRs will be skipped (default: false)
          skip-with-manual-reviewers: 2 # Skip this action, if the number of reviwers was already assigned (default: 0)
