name: Default

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  lint:
    name: Lint and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - run: yarn lint
      - run: yarn test
