name: Check

on:
  push:
    branches: [main, develop]
  pull_request:

env:
  INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}
  MNEMONIC: ${{secrets.MNEMONIC}}

jobs:
  lint:
    name: Contracts - Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - run: yarn lint
  coverage:
    name: Contracts - Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - run: yarn coverage
